config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'simulators/index'
  get 'simulators/apv', as: 'apv'
  post "simulators/apv" => "simulators#create"
  get 'simulators/apo', as: 'apo'
  post "simulators/apo" => "simulators#create"
  get 'simulators/resultadoAPO' => 'resultadoAPO', as: 'resultadoAPO'
  get 'simulators/resultadoAPV' => 'resultadoAPV', as: 'resultadoAPV'


  #get 'simulators/resultado'
  root to: 'simulators#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simulador.rb
class Simulador < ApplicationRecord
  validates :nombre, :edad, :sexo, :sueldo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/simulators_controller.rb
class SimulatorsController < ApplicationController

  def new
    @simulator = Simulador.new
  end


  def calcularMeses(edad, sexo)
    if sexo=='Masculino'
      return (65-edad)
    else
      return (60-edad)
    end
  end

  def APO(edad, sexo, apo, sueldo) #APO final
    tiempo = calcularMeses(edad, sexo)
    for i in 1..tiempo
      apo = apo + ((sueldo*0.1)*12)
      apo = apo*(1.05)
    end
    return apo
  end

  def APV(edad, sexo, sueldo, apo, pensionDeseada) #APV necesario para monto deseado
    if sexo == 'Masculino'
      return pensionDeseada*240 - APO(edad, sexo, apo, sueldo)
    else
      return pensionDeseada*360 - APO(edad, sexo, apo, sueldo)
    end
  end

  def APV_mensual(edad, sexo, sueldo, apo, pensionDeseada) #APV mensual para monto deseado
    tiempo = calcularMeses(edad,sexo)
    apvAcumulado = APV(edad, sexo, sueldo, apo, pensionDeseada)
    for i in 1...tiempo
      apvAcumulado = apvAcumulado - (apvAcumulado*0.15)
    end
    return (apvAcumulado/12).abs
  end

  def APV_final(edad, sexo, apvAcumulado, apvMensual) #APV final dado un fondo (puede ser 0) y una cantidad de dinero mensual
    tiempo = calcularMeses(edad, sexo)
    for i in 1..tiempo
      apvAcumulado = apvAcumulado + (apvMensual*12)
      apvAcumulado = apvAcumulado*1.05
    end
    return apvAcumulado
  end

  def pension_mensual(fondo, sexo)
    if sexo=='Masculino'
      periodo = 20*12
      fondo/periodo
    else
      periodo = 30*12
      fondo/periodo
    end
  end

  def resultadoAPO
    @simulacion = Simulador.find(params[:id])
    @simulaciones = Array.new(2)
    @simulaciones[0] = APO(@simulacion.edad,@simulacion.sexo,@simulacion.apo,@simulacion.sueldo) + APV_final(@simulacion.edad,@simulacion.sexo, @simulacion.apvAcumulado, @simulacion.apvMensual)
    @simulaciones[1] = pension_mensual(@simulaciones[0], @simulacion.sexo)
  end

  def resultadoAPV
    @simulacion = Simulador.find(params[:id])
    @simulaciones = Array.new(1)
    @simulaciones[0] = @simulacion.pensionDeseada
    @simulaciones[1] = APV_mensual(@simulacion.edad, @simulacion.sexo, @simulacion.sueldo, APO(@simulacion.edad,@simulacion.sexo,@simulacion.apo,@simulacion.sueldo), @simulacion.pensionDeseada )


  end

  def create
    @simulacion = Simulador.new(simulador_params)
    if @simulacion.pensionDeseada.nil?
      @simulacion.pensionDeseada = 0
      @simulacion.save
      redirect_to :action => 'resultadoAPO', :id => @simulacion.id
    else
      @simulacion.apvMensual=0
      @simulacion.apvAcumulado=0
      @simulacion.save
      redirect_to :action => 'resultadoAPV', :id => @simulacion.id
    end
  end

  private
  def simulador_params
    params.require(:simulador).permit(:nombre, :edad, :sexo, :apo, :sueldo, :apvMensual, :apvAcumulado, :pensionDeseada)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simulators_helper.rb
module SimulatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RetirementSimulator</title>
    <title>Simulator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simulators/_form.html.erb
<div class='container'>
  <%= bootstrap_form_for :simulador do |f| %>
    <%= f.text_field :nombre %>
    <%= f.number_field :edad, in: 18..65, step: 1 %>
    <%= f.form_group :sexo, label: { text: "Sexo" } do %>
      <%= f.radio_button :sexo, 'Masculino', label: "Masculino", checked: true %>
      <%= f.radio_button :sexo, 'Femenino', label: "Femenino" %>
    <% end %>
    <%= f.number_field :sueldo, label: "Sueldo" %>
    <%= f.number_field :apo, label: "Ahorro previsional obligatorio acumulado" %>
    <%= f.number_field :apvMensual, label: "Ahorro previsional voluntario mensual" %>
    <%= f.number_field :apvAcumulado, label: "Ahorro previsional voluntario acumulado" %>
    <%= f.number_field :pensionDeseada, label: "Pensión deseada %>
    <%= f.submit "Calcular" %>
  <% end %>
</div>

app/views/simulators/apo.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-4 offset-md-4'>
      <center>
        <h1>Retirement Simulator</h1>
      </center>
    </div>
  </div>
  <p></p>
  <div class="row">
    <%= bootstrap_form_for :simulador do |f| %>
      <%= f.text_field :nombre %>
      <%= f.number_field :edad, value: 18, in: 18..65, step: 1 %>
      <%= f.form_group :sexo, label: { text: "Sexo" } do %>
        <%= f.radio_button :sexo, 'Masculino', label: "Masculino", checked: true %>
        <%= f.radio_button :sexo, 'Femenino', label: "Femenino" %>
      <% end %>
      <%= f.number_field :sueldo, value: 0,  label: "Sueldo" %>
      <%= f.number_field :apo, value: 0, label: "Ahorro previsional obligatorio acumulado" %>
      <%= f.number_field :apvMensual, value: 0, label: "Ahorro previsional voluntario mensual" %>
      <%= f.number_field :apvAcumulado, value: 0, label: "Ahorro previsional voluntario acumulado" %>
      <%= f.submit "Calcular" %>
    <% end %>
  </div>
</div>

app/views/simulators/apv.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-4 offset-md-4'>
      <center>
        <h1>Retirement Simulator</h1>
      </center>
    </div>
  </div>
  <p></p>
  <div class="row">
    <%= bootstrap_form_for :simulador do |f| %>
      <%= f.text_field :nombre %>
      <%= f.number_field :edad, value:18,  in: 18..65, step: 1 %>
      <%= f.form_group :sexo, label: { text: "Sexo" } do %>
        <%= f.radio_button :sexo, 'Masculino', label: "Masculino", checked: true %>
        <%= f.radio_button :sexo, 'Femenino', label: "Femenino" %>
      <% end %>
      <%= f.number_field :sueldo, value: 0, label: "Sueldo" %>
      <%= f.number_field :apo,value: 0,  label: "Ahorro previsional obligatorio acumulado" %>
      <%= f.number_field :pensionDeseada, value: 0, label: "Pensión deseada" %>
      <%= f.submit "Calcular" %>
    <% end %>
  </div>
</div>

app/views/simulators/index.html.erb
<div class='container'>
  <div class='row'>

      <center>
        <h1>Retirement Simulator</h1>
      </center>

  </div>
  <p></p>
  <div class='row'>

      <div class='btn btn-default btn-block'>
        <%= link_to "Calcular monto pensión", apo_path, :class => "btn" %>
      </div>
      <div class='btn btn-default btn-block'>
        <%= link_to "Calcular APV mensual", apv_path, :class => "btn" %>
      </div>

  </div>
</div>

app/views/simulators/resultadoAPO.html.erb
<div class='container'>
  <div class='row'>
    <center>
      <div class='col-md-12'>
        <h1>Retirement Simulator</h1>
      </div>
    </center>
  </div>
  <p></p>
  <row>
    <center>
      <p>
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      </p>
      </br>
      <p>
        Monto total ahorro previsional obligatorio</br>
        <big>$<%= @simulaciones[0].to_i %></big>
      </p>
      <hr>
      <p>
        Monto a recibir mensualmente</br>
        <big>$<%= @simulaciones[1].to_i %></big>
      </p>
      <hr>
      <p> Para realizar una nueva simulación haga <%= link_to 'click aquí', root_path %></p>
    </center>
  </row>
</div>

app/views/simulators/resultadoAPV.html.erb
<div class='container'>
  <div class='row'>
    <center>
      <div class='col-md-12'>
        <h1>Retirement Simulator</h1>
      </div>
    </center>
  </div>
  <p></p>
  <row>
    <center>
      <p>
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      </p>
      </br>
      <p>
        Pensión deseada</br>
        <big>$<%= @simulaciones[0] %></big>
      </p>
      <hr>
      <p>
        Monto a ahorrar mensualmente en su APV para obtener la pensión deseada</br>
        <big>$<%= @simulaciones[1].to_i %></big>
        </br>
      </p>
      <hr>
      <p> Para realizar una nueva simulación haga <%= link_to 'click aquí', root_path %></p>
    </center>
  </row>
</div>